name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize:
    uses: GEWIS/actions/.github/workflows/docker-build.yml@v0.0.2
    with:
      projects: '["."]'