name: Lint and Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    uses: GEWIS/actions/.github/workflows/typescript-yarn-lint-and-build.yml@e16e0f26bd1d7b5efc72961dbe09267978a9fbf3
